config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :categories do
    resources :projects, except: [:index]
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	load_and_authorize_resource

	def index
	end

	def new
		@post = Post.find(params[:post_id])
		@comment = Comment.new
		respond_to do |format|
			format.html
			format.js
		end
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		@comment.user = current_user
		@comments = current_user.comments
		respond_to do |format|
			if @comment.save
				flash[:notice] = "Comment successfully added"
				format.html {redirect_to post_path(@post)}
				format.js
			else
				flash[:alert] = "Something went wrong"
				format.html
				format.js
			end
		end
	end

	def show
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		if @comment.update(comment_params)
			flash[:notice] = "Comment successfully edited"
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		flash[:notice] = "Comment successfully deleted"
		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment], remote: true) do |f| %>
	<div class="form-group">
		<%= f.label :body, "Comment" %>
		<%= f.text_area :body, class: "form-control" %>
	</div>

	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/comments/_list.html.erb
<% if @comments.any? %>
		<ul id="comments_list">
			<% @comments.each do |comment| %>
				<li><%= comment.body %> - <%= link_to "View more", post_comment_path(@post, comment)  %></li>
			<% end %>
		</ul>
	<% else %>
		<p>There are no comments</p>
	<% end %>

app/views/comments/create.js.erb
$("#comments_container").html("<%= j render 'comments/list' %>");
$("form#new_comment").remove();
$("#new_comment_link").show();

app/views/comments/edit.html.erb
<%= render 'layouts/errors', object: @comment %>
<%= render 'form' %>

app/views/comments/new.html.erb
<%= render 'layouts/errors', object: @comment %>
<%= render 'form' %>

app/views/comments/new.js.erb
$("#new_comment_link").hide();
$("#comment_form_container").append("<%= j render 'form' %>");

app/views/comments/show.html.erb
<p>
	<%= @comment.body %>
</p>

<% if current_user == @comment.user %>
<ul class="nav nav-pills">
	<li role="presentation"><%= link_to "Edit", edit_post_comment_path(@post, @comment) %></li>
	<li role="presentation"><%= link_to "Delete", post_comment_path(@post, @comment), data: { confirm: "Are you sure?" }, method: :delete %></li>
</ul>
<% end %>