config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :categories do
    resources :projects, except: [:index]
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	load_and_authorize_resource

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "Post has been successfully added"
			redirect_to post_path(@post)
		else
			flash[:alert] = "Something went wrong"
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments
		@comment = Comment.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			flash[:notice] = "Post has been successfully edited"
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:notice] = "Post has been deleted"
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/views/posts/_form.html.erb
<h1>New Blog Post</h1>

<%= form_for(@post) do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: "form-control" %>
	</div>
	<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'layouts/errors', object: @post %>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1><u>My Blog</u></h1>
<br><br><br>
	<% @posts.each do |post| %>
		<h3><%= link_to post.title, post_path(post) %></h3>
	<% end %>

app/views/posts/new.html.erb
<div class="well">
  <%= render 'layouts/errors', object: @post %>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<div class="comments">
	<p><b><i>Comments</i></b></p>
	<div id="comments_container">
		<%= render 'comments/list' %>
	</div>


	<div id="comment_form_container">
		<% if user_signed_in? %>
	</div>
</div>


<% if can? :mangage, Post %>
	<div class="admin">
		<nav>
			<ul class="nav nav-pills">
				<%= link_to "New comment", new_post_comment_path(@post, @comment), id: "new_comment_link", remote: true  %>
				<% else %>
				<p>Please sign in to add a comment.</p>
				<% end %>
				<li role="presentation"><%= link_to "Edit", edit_post_path(@post) %></li>
				<li><%= link_to "Delete", post_path(@post), data: { confirm: "Are you sure?" }, method: :delete %></li>
			</ul>
		</nav>
	</div>
<% end %>