config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :categories do
    resources :projects, except: [:index]
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects, dependent: :destroy

  validates :name, :presence => true
  validates :description, :presence => true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  def index
    @categories = Category.all
    @recommendations = Recommendation.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Category successfully added!"
        redirect_to  categories_path
      else
        render :new
      end
    end

    def edit
    @category = Category.find(params[:id])
  end

  def update
    @category= Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category successfully updated!"
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
   @category = Category.find(params[:id])
   @category.destroy
   redirect_to categories_path
 end

    private
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/views/categories/_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= bootstrap_form_for @category do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'layouts/errors', object: @category %>
<%= render "form" %>

app/views/categories/index.html.erb
<div class="well">
<h1>Spiral out, keep going.</h1>

<h3>My name is Leon Zagorouiko and I'm currently attending Epicodus.</h3>
<ul>
  <li><h2>github: https://github.com/Zagorouiko</h2></li>
</ul>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class="jumbotron">
<h2>Reference ScoreBoard</h2>
	<div id="recommendation_form_container">
	</div>
	<% if user_signed_in? %>
		<p><%= link_to "Add recommendation", new_recommendation_path, id: "new_recommendation_link", remote: true %><p>
	<% else %>
		<h3>Please sign in to add a recommendation.</h3>
	<% end %>
		<div id="recommendations_list">
      <ul>
        <% @recommendations.each do |recommendation| %>
          <h4><div class="recom" <%= image_tag(recommendation.user.avatar) %></div><b><%= recommendation.description %></b> - <b><%= recommendation.user.username %></b></h4>
        <% end %>
      </ul>
    </div>
  </div>

app/views/categories/new.html.erb
<div class="well">
<h1>New Skill</h1>
<%= render 'layouts/errors', object: @category %>
<%= render "form" %>
</div>

app/views/categories/show.html.erb
<div class="well">
<h1><u><%= @category.name %></u></h1>
    <p><b><%= @category.description %><b></p>

<h3><u>Projects</u></h3>

  <% if @category.projects.any? %>
    <ul>
      <% @category.projects.each do |project| %>
        <li><%= link_to project.name, category_project_path(@category, project) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no projects.</p>
  <% end %>

  <br>

<%= link_to 'Add a Project', new_category_project_path(@category) %> |
<%= link_to 'Edit Category', edit_category_path(@category) %> |
<%= link_to 'Delete Category', category_path(@category), data: { confirm: "Are you sure?", method: "delete"} %>
</div>