config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :categories do
    resources :projects, except: [:index]
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @category %>

<%= bootstrap_form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Orbitron" />
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <%- end -%>
  <div class="wrapper">
    <div class="box">
      <div class="row row-offcanvas row-offcanvas-left">
      <!-- <nav class="navbar navbar-inverse navbar-fixed-top"> -->
        <div class="column col-sm-2 col-xs-1 sidebar-offcanvas" id="sidebar">
          <%= image_tag("profile.jpg", class: "img-responsive") %>

      <ul class="nav">
        <ul class="nav hidden-xs" id="lg-menu">
        <li><%= link_to "Home", categories_path %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li>_________ </li>
        <li>Projects</li>
        <% Category.all.each do |category| %>
        <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
        <% if can? :manage, Category %>
        <li>__________</li>
        <li>Admin</li>
        <li><%= link_to "Add Skill", new_category_path %></li>
        <li><%= link_to "Add Post", new_post_path %></li>
        <% end %>
        <% if user_signed_in? %>
        <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
        <li><i class="glyphicon glyphicon-heart-empty"></i><%= current_user.email %></li>
        <div class="stuff"><%= link_to 'Edit profile', edit_user_registration_path %> | <%= link_to "Logout", destroy_user_session_path, method: :delete %></div>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>


      </ul>
    </ul>
    <ul class="list-unstyled hidden-xs" id="sidebar-footer">
    </ul>
    <!-- </nav> -->
    </div>
    <div class="column col-sm-10 col-xs-11" id="main">
        <div class="full col-sm-9">
          <div class="row">
            <%= yield %>
          </div>
        </div>
    </div>
   </div>
  </div>
 </div>

</body>
</html>